fix: checks for github action for EBSI Issuance CT tests

diff --git a/.github/workflows/ebsictv3.yml b/.github/workflows/ebsictv3.yml
--- a/.github/workflows/ebsictv3.yml
+++ b/.github/workflows/ebsictv3.yml
@@ -16,9 +16,9 @@ jobs:
   EBSI-Conformance-Test-v3:
     runs-on: ubuntu-latest
     steps:
-      - name: The EBSI Confornace Test v3.2 job is starting
+      - name: The EBSI Conformance Test v3.2 job is starting
         run: |
-          echo -e "🔎 The EBSI Confornace Test v3.2 job is starting\n"
+          echo -e "🔎 The EBSI Conformance Test v3.2 job is starting\n"
       - name: Docker
         run: docker --version
 
@@ -33,7 +33,13 @@ jobs:
       - name: Update config files and start Issuer API
         run: |
           NGROK_URL=$(curl --retry 5 --retry-delay 5 --retry-connrefused -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
-          echo "The ngork url is ${NGROK_URL}"       
+          
+          if [[ -z "$NGROK_URL" ]]; then
+            echo "Error: Failed to fetch ngrok URL. Exiting..."
+          exit 1
+          fi
+
+          echo "The ngork url is ${NGROK_URL}\n"       
 
           sed -i 's|readonly ISSUER_URL=".*"|readonly ISSUER_URL="'"${NGROK_URL}"'"|g' .github/workflows/ebsictv3/EBSICTV3-IssueToHolder.sh
           sed -i 's|baseUrl = ".*"|baseUrl = "'"${NGROK_URL}"'"|g' waltid-services/waltid-issuer-api/config/issuer-service.conf
@@ -46,7 +52,7 @@ jobs:
           ISSUER_URL=$(curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:7002/draft11/.well-known/openid-credential-issuer | jq -r '.issuer')
 
           if [[ "$ISSUER_URL" == "${NGROK_URL}/draft11" ]]; then
-            echo -e "\nIssuer URL is valid: $ISSUER_URL\n"
+            echo -e "\nIssuer URL is valid: ${ISSUER_URL}\n"
           else
             echo -e "\nIssuer URL is invalid (matches forbidden value): $ISSUER_URL and "${NGROK_URL}/draft11"\n"
             exit 1
