feat: checks for github action for EBSI Issuance CT tests

diff --git a/.github/workflows/ebsictv3.yml b/.github/workflows/ebsictv3.yml
--- a/.github/workflows/ebsictv3.yml
+++ b/.github/workflows/ebsictv3.yml
@@ -37,17 +37,19 @@ jobs:
           sed -i 's|readonly ISSUER_URL=".*"|readonly ISSUER_URL="'"${NGROK_URL}"'"|g' .github/workflows/ebsictv3/EBSICTV3-IssueToHolder.sh
           sed -i 's|baseUrl = ".*"|baseUrl = "'"${NGROK_URL}"'"|g' waltid-services/waltid-issuer-api/config/issuer-service.conf
 
-      - name: Start Issuer API
-        run: |
-          echo "The ngork url is ${NGROK_URL}"       
-
           docker build -t waltid/issuer-api:latest -f waltid-services/waltid-issuer-api/Dockerfile .
           docker run --net=host  -d -p 7002:7002 -v $PWD/waltid-services/waltid-issuer-api/config:/waltid-issuer-api/config --name waltid-issuer-api waltid/issuer-api:latest
           
           curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:7002/livez
 
-          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:7002/draft11/.well-known/openid-credential-issuer | jq -r '.issuer'
+          ISSUER_URL=$(curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:7002/draft11/.well-known/openid-credential-issuer | jq -r '.issuer')
 
+          if [[ "ISSUER_URL" == "${NGROK_URL}/draft11" ]]; then
+            echo "Issuer is valid: $result"
+          else
+            echo "Issuer is invalid (matches forbidden value): $ISSUER_URL"
+            exit 1
+          fi
 
       - name: Execute test scripts
         env:
